# Generated by Django 2.2.6 on 2020-06-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20200602_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to='employee'),
        ),
    ]
