# Generated by Django 2.2.6 on 2020-06-03 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20200603_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to='employee'),
        ),
    ]
