# Generated by Django 2.2.6 on 2020-07-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20200713_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('HOLD', 'Hold'), ('IN PROGRESS', 'IN PROGRESS'), ('COMPLETE', 'Complete'), ('ARCHIVE', 'archive'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10),
        ),
    ]
