# Generated by Django 5.0.4 on 2024-04-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20200713_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('HOLD', 'Hold'), ('IN PROGRESS', 'In Progress'), ('COMPLETE', 'Complete'), ('ARCHIVE', 'archive'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=255),
        ),
    ]
